In [8]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

Ts = 100/1000

Ad = np.matrix([[1,Ts,0.5*(Ts*Ts)],
                  [0,1,Ts],
                  [0,0,1]])
print (Ad)
# # Bd = np.array ([0],
#                [0],
#                [1]) # control input only in acceleration

G = np.matrix ([[1,2,3],[0,1,0],[0,0,1]])

Gd = Ad * G
print (Gd)

print(G[:,0])


[[1.    0.1   0.005]
 [0.    1.    0.1  ]
 [0.    0.    1.   ]]
[[1.    2.1   3.005]
 [0.    1.    0.1  ]
 [0.    0.    1.   ]]
[[1]
 [0]
 [0]]


In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

l=1000
t = np.linspace(0, 100, l)
print (len(t))

a = 10 % 3 
print(a)

1000
1
